
// Main ActionTypes
export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR';
export const TOGGLE_ADMIN_CONTEXT_MENU = 'TOGGLE_USER_CONTEXT_MENU';
export const CHANGE_PATH = 'CHANGE_PATH';
export const CHANGE_TOPBAR_TITLE = 'CHANGE_TOPBAR_TITLE';

// Summary ActionTypes
export const REQUEST_USERS_METRICS = 'REQUEST_USERS_METRICS';
export const RECEIVE_USERS_METRICS = 'RECEIVE_USERS_METRICS';

export const REQUEST_DATABASE_METRICS = 'REQUEST_DATABASE_METRICS';
export const RECEIVE_DATABASE_METRICS = 'RECEIVE_DATABASE_METRICS';

export const REQUEST_PLIVO_DATA = 'REQUEST_PLIVO_DATA';
export const RECEIVE_PLIVO_DATA = 'RECEIVE_PLIVO_DATA';

// Forms ActionTypes

// Notice
export const NOTICE_ACTION_CHANGE = 'NOTICE_ACTION_CHANGE';

export const REQUEST_NOTICES = 'REQUEST_NOTICES';
export const REQUEST_NOTICES_COUNT = 'REQUEST_NOTICES_COUNT';
export const RECEIVE_NOTICES = 'RECEIVE_NOTICES';
export const RECEIVE_NOTICES_COUNT = 'RECEIVE_NOTICES_COUNT';

export const INSERT_NOTICE_REQUEST_AGENCY_SEARCH = 'INSERT_NOTICE_REQUEST_AGENCY_SEARCH';
export const INSERT_NOTICE_RECEIVE_AGENCY_SEARCH = 'INSERT_NOTICE_RECEIVE_AGENCY_SEARCH';
export const INSERT_NOTICE_AGENCY_SEARCH_CLEAR = 'INSERT_NOTICE_AGENCY_SEARCH_CLEAR';

export const SEARCH_NOTICE_FILTER_CHANGE = 'SEARCH_NOTICE_FILTER_CHANGE';
export const SEARCH_NOTICE_FILTER_CLEAR = 'SEARCH_NOTICE_FILTER_CLEAR';
export const SEARCH_NOTICE_PAGINATION_CHANGE = 'SEARCH_NOTICE_PAGINATION_CHANGE';
export const SEARCH_NOTICE_SELECTED_CHANGE = 'SEARCH_NOTICE_SELECTED_CHANGE';

export const EDIT_NOTICE_SET = 'EDIT_NOTICE_SET';

// Segment
export const SEGMENT_ACTION_CHANGE = 'SEGMENT_ACTION_CHANGE';
export const INSERT_SEGMENT_SUCCESS = 'INSERT_SEGMENT_SUCCESS';
export const INSERT_SEGMENT_FAIL = 'INSERT_SEGMENT_FAIL';
export const INSERT_SEGMENT_CLEAR = 'INSERT_SEGMENT_CLEAR';
export const INSERT_SEGMENT_NAME_CHANGE = 'INSERT_SEGMENT_NAME_CHANGE';
export const SEARCH_SEGMENT_FILTER_CHANGE = 'SEARCH_SEGMENT_FILTER_CHANGE';
export const SEARCH_SEGMENT_VIEW_STYLE_CHANGE = 'SEARCH_SEGMENT_VIEW_STYLE_CHANGE';

export const REQUEST_INSERT_SEGMENT = 'REQUEST_INSERT_SEGMENT';

export const EDIT_SEGMENT = 'EDIT_SEGMENT';
export const EDIT_SEGMENT_SET = 'EDIT_SEGMENT_SET';
export const EDIT_SEGMENT_NAME_CHANGE = 'EDIT_SEGMENT_NAME_CHANGE';

export const DELETE_SEGMENT = 'DELETE_SEGMENT';
export const REQUEST_SEGMENTS = 'REQUEST_SEGMENTS';
export const REQUEST_SEGMENTS_COUNT = 'REQUEST_SEGMENTS_COUNT';
export const RECEIVE_SEGMENTS_COUNT = 'RECEIVE_SEGMENTS_COUNT';
export const RECEIVE_SEGMENTS = 'RECEIVE_SEGMENTS';
export const SEGMENT_FILTER_CHANGE = 'SEGMENT_FILTER_CHANGE';

// Agency
export const AGENCY_ACTION_CHANGE = 'AGENCY_ACTION_CHANGE';
export const SEARCH_AGENCY_SORT_CHANGE = 'SEARCH_AGENCY_SORT_CHANGE';
export const SEARCH_AGENCY_PAGINATION_CHANGE = 'SEARCH_AGENCY_PAGINATION_CHANGE';

export const INSERT_AGENCY_CLEAR = 'INSERT_AGENCY_CLEAR';
export const INSERT_AGENCY_INITIALS_CHANGE = 'INSERT_AGENCY_INITIALS_CHANGE';
export const INSERT_AGENCY_NAME_CHANGE = 'INSERT_AGENCY_NAME_CHANGE';
export const INSERT_AGENCY_CITY_CHANGE = 'INSERT_AGENCY_CITY_CHANGE';

export const EDIT_AGENCY = 'EDIT_AGENCY';
export const EDIT_AGENCY_SET = 'EDIT_AGENCY_SET';
export const EDIT_AGENCY_NAME_CHANGE = 'EDIT_AGENCY_NAME_CHANGE';
export const EDIT_AGENCY_INITIALS_CHANGE = 'EDIT_AGENCY_INITIALS_CHANGE';
export const EDIT_AGENCY_CITY_CHANGE = 'EDIT_AGENCY_CITY_CHANGE';

export const REQUEST_AGENCIES = 'REQUEST_AGENCIES';
export const RECEIVE_AGENCIES = 'RECEIVE_AGENCIES';
export const REQUEST_AGENCIES_COUNT = 'REQUEST_AGENCIES_COUNT';
export const RECEIVE_AGENCIES_COUNT = 'RECEIVE_AGENCIES_COUNT';

// Location
export const LOCATION_ACTION_CHANGE = 'LOCATION_ACTION_CHANGE';

export const INSERT_LOCATION = 'INSERT_LOCATION';
export const INSERT_LOCATION_SUCCESS = 'INSERT_LOCATION_SUCCESS';
export const INSERT_LOCATION_FAIL = 'INSERT_LOCATION_FAIL';
export const INSERT_LOCATION_CHANGE = 'INSERT_LOCATION_CHANGE';

export const EDIT_CITY_CHANGE = 'EDIT_CITY_CHANGE';
export const EDIT_STATE_CHANGE = 'EDIT_STATE_CHANGE';

export const SEARCH_LOCATION_LIMIT_CHANGE = 'SEARCH_LOCATION_LIMIT_CHANGE';
export const SEARCH_LOCATION_FILTER_CHANGE = 'SEARCH_LOCATION_FILTER_CHANGE';
export const SEARCH_LOCATION_FILTER_CLEAR = 'SEARCH_LOCATION_FILTER_CLEAR';
export const SEARCH_LOCATION_SORT_CHANGE = 'SEARCH_LOCATION_SORT_CHANGE';

export const REQUEST_INSERT_LOCATION = 'REQUEST_INSERT_LOCATION';

export const REQUEST_STATES = 'REQUEST_STATES';
export const RECEIVE_STATES = 'RECEIVE_STATES';
export const REQUEST_CITIES = 'REQUEST_CITIES';
export const RECEIVE_CITIES = 'RECEIVE_CITIES';
export const REQUEST_CITIES_FROM_STATE = 'REQUEST_CITIES_FROM_STATE';
export const RECEIVE_CITIES_FROM_STATE = 'RECEIVE_CITIES_FROM_STATE';

// Users ActionTypes
export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';
export const REQUEST_USERS_COUNT = 'REQUEST_USERS_COUNT';
export const RECEIVE_USERS_COUNT = 'RECEIVE_USERS_COUNT';
export const REQUEST_NEWEST_USERS = 'REQUEST_NEWEST_USERS';
export const RECEIVE_NEWEST_USERS = 'RECEIVE_NEWEST_USERS';

export const USERS_SELECT_CHANGE = 'USERS_SELECT_CHANGE';

export const USERS_ALL_VIEW_STYLE_CHANGE = 'USERS_ALL_VIEW_STYLE_CHANGE';
export const USERS_ALL_SORT_CHANGE = 'USERS_ALL_SORT_CHANGE';
export const USERS_ALL_FILTER_CHANGE = 'USERS_ALL_FILTER_CHANGE';
export const USERS_ALL_FILTER_CLEAR = 'USERS_ALL_FILTER_CLEAR';
export const USERS_ALL_LIMIT_CHANGE = 'USERS_ALL_LIMIT_CHANGE';
export const USERS_ALL_PAGE_CHANGE = 'USERS_ALL_PAGE_CHANGE';

// Tools ActionTypes

// Scraper

export const SCRAPER_ACTION_CHANGE = 'SCRAPER_ACTION_CHANGE';
export const SCRAPER_PAGE_CHANGE = 'SCRAPER_PAGE_CHANGE';

export const SCRAPER_TOGGLE_BAR_VISIBILITY = 'SCRAPER_TOGGLE_BAR_VISIBILITY';
export const SCRAPER_TOGGLE_BAR_EXPAND = 'SCRAPER_TOGGLE_BAR_EXPAND';
export const SCRAPER_SELECT_CHANGE = 'SCRAPER_SELECT_CHANGE';
export const SCRAPER_REQUEST_RUN = 'SCRAPER_REQUEST_RUN';
export const SCRAPER_RECEIVE_RUN = 'SCRAPER_RECEIVE_RUN';
export const SCRAPER_START = 'SCRAPER_START';
export const SCRAPER_FINISH = 'SCRAPER_FINISH';
export const SCRAPER_UPDATE_STATS = 'SCRAPER_UPDATE_STATS';
export const SCRAPER_REQUEST_LAST_RUN_SCRAPERS = 'SCRAPER_REQUEST_LAST_RUN_SCRAPERS';
export const SCRAPER_RECEIVE_LAST_RUN_SCRAPERS = 'SCRAPER_RECEIVE_LAST_RUN_SCRAPERS';

export const SCRAPER_REQUEST_PENDING_RESULTS = 'SCRAPER_REQUEST_PENDING_RESULTS';
export const SCRAPER_RECEIVE_PENDING_RESULTS = 'SCRAPER_RECEIVE_PENDING_RESULTS';
export const SCRAPER_RESULTS_SHOW_IGNORE_CHANGE = 'SCRAPER_RESULTS_SHOW_IGNORE_CHANGE';
export const SCRAPER_RESULT_REQUEST_DETECT_SEGMENT = 'SCRAPER_RESULT_REQUEST_DETECT_SEGMENT';
export const SCRAPER_RESULT_RECEIVE_DETECT_SEGMENT = 'SCRAPER_RESULT_RECEIVE_DETECT_SEGMENT';
export const SCRAPER_RESULT_CHANGE_SEGMENT = 'SCRAPER_RESULT_CHANGE_SEGMENT';
export const SCRAPER_RESULT_UPDATE_SEGMENT = 'SCRAPER_RESULT_UPDATE_SEGMENT';
export const SCRAPER_RESULT_CHANGE_SEGMENT_CONFIRM = 'SCRAPER_RESULT_CHANGE_SEGMENT_CONFIRM';
export const SCRAPER_RESULT_CHANGE_SEGMENT_CANCEL = 'SCRAPER_RESULT_CHANGE_SEGMENT_CANCEL';
export const SCRAPER_RESULT_CHANGE_AMOUNT = 'SCRAPER_RESULT_CHANGE_AMOUNT';
export const SCRAPER_RESULT_UPDATE_AMOUNT = 'SCRAPER_RESULT_UPDATE_AMOUNT';
export const SCRAPER_RESULT_CHANGE_AMOUNT_CONFIRM = 'SCRAPER_RESULT_CHANGE_AMOUNT_CONFIRM';
export const SCRAPER_RESULT_CHANGE_AMOUNT_CANCEL = 'SCRAPER_RESULT_CHANGE_AMOUNT_CANCEL';

export const SCRAPER_RESULT_UPDATE_IGNORE = 'SCRAPER_RESULT_UPDATE_IGNORE';

// Neural ActionTypes
export const NEURAL_ADD_INPUT = 'NEURAL_ADD_INPUT';
export const NEURAL_REMOVE_INPUT = 'NEURAL_REMOVE_INPUT';
export const NEURAL_UPDATE_INPUT = 'NEURAL_UPDATE_INPUT';
export const NEURAL_UPDATE_OUTPUT = 'NEURAL_UPDATE_OUTPUT';
             
// Admin ActionTypes
export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

// Modal ActionTypes
export const SHOW_MODAL_WITH_COMPONENT = 'SHOW_MODAL_WITH_COMPONENT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_MODAL_TEXT = 'SET_MODAL_TEXT';
export const SET_MODAL_TITLE = 'SET_MODAL_TITLE';
export const SET_MODAL = 'SET_MODAL';
export const RESET_MODAL = 'RESET_MODAL';